name: project_teachers
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.14.0+5
  firebase_messaging: ^6.0.12
  cloud_firestore:
    git:
      url: https://github.com/pY4x3g/flutterfire.git
      ref: bd4007a28b27fc5838d2849dae6ba875a8b635e2
      path: packages/cloud_firestore/cloud_firestore
  shared_preferences: ^0.5.2+1
  image_picker: ^0.6.3+1
  provider: ^4.0.4
  flutter_speed_dial: ^1.2.5
  synchronized_lite: ^1.0.0+2
  flutter_google_places: ^0.2.4
  google_maps_webservice: ^0.0.16
  firebase_storage: ^3.1.5
  grouped_buttons: ^1.0.4
  tuple: ^1.0.3
  image_cropper: ^1.2.1
  fluttertoast: ^4.0.0
  flutter_typeahead: ^1.8.1
  connectivity: ^0.4.8+6
  keyboard_visibility: ^0.5.6
  cached_network_image: ^2.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

   #To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/connection-lost.png
    - assets/img/logo.png
    - assets/img/lang/lang_en.png
    - assets/img/lang/lang_nl.png
    - assets/img/default_background.jpg
    - assets/img/default_profile.png
    - assets/img/default_profile_2.png
    - assets/img/icon_new.png
    - assets/img/timeline/comment.png
    - assets/img/timeline/comment2.png
    - assets/img/timeline/like_enabled.png
    - assets/img/timeline/like_disabled.png
    - locale/i18n_en.json
    - locale/i18n_nl.json
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #fonts:
  #  - family: Helvetica
  #    fonts:
  #      - asset: fonts/HelveticaNeue_Medium.ttf
  #      - asset: fonts/HelveticaNeueIt.ttf
  #        style: italic
  #      - asset: fonts/HelveticaNeue_Medium.ttf
  #        weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
